### ISSUE TITLE
Attempt to write a readonly database error from /create

### ISSUE THREAD

**Issue by Namaskar-1F64F** [Syfaro/selectionsbot#2]
Hello, found the bot from reddit! Does not seem to work right now :|
![image](https://user-images.githubusercontent.com/7458951/51404693-30054300-1b22-11e9-8734-4c81ddb6ec69.png)

**Comment by Syfaro** [comment]
Try it now, think it should be working again.

**Comment by Namaskar-1F64F** [comment]
Yep, looks like it's working, thanks!
